/** Data mirrored from PageController + fintech service catalogue */
export const serviceStats = [
  { value: "4+", label: "Years leadership" },
  { value: "10+", label: "Relationships" },
  { value: "25+", label: "Platforms" },
  { value: "12", label: "Service lines" },
];

export const services = [
  {
    id: "web",
    icon: "fas fa-laptop-code",
    title: "Web & System Design & Development",
    copy: "User-friendly, secure, and scalable systems and websites.",
    cta: "#consult",
  },
  {
    id: "systems",
    icon: "fas fa-cogs",
    title: "System Design & Development",
    copy: "Customised solutions tailored to optimise business processes and efficiency.",
    cta: "#consult",
  },
  {
    id: "uiux",
    icon: "fas fa-paint-brush",
    title: "Graphic Design & UI/UX Design",
    copy: "Creative visuals and intuitive interfaces to enhance brand impact.",
    cta: "#consult",
  },
  {
    id: "support",
    icon: "fas fa-headset",
    title: "IT Support Services",
    copy: "Reliable technical support for smooth and efficient operations.",
    cta: "#consult",
  },
  {
    id: "accounting",
    icon: "fas fa-file-invoice-dollar",
    title: "Computerised Accounting Solutions",
    copy: "Streamlined financial management for accurate and efficient reporting.",
    cta: "#consult",
  },
  {
    id: "microfinance",
    icon: "fas fa-hand-holding-usd",
    title: "Microfinance Solutions",
    copy: "Loan, savings, and member workflows for MFIs and community lenders.",
    cta: "#consult",
  },
  {
    id: "ecommerce",
    icon: "fas fa-shopping-cart",
    title: "E-Commerce Solutions",
    copy: "Storefronts, inventory, cart, checkout, and catalogue operations for digital sales.",
    cta: "#consult",
  },
  {
    id: "isp",
    icon: "fas fa-wifi",
    title: "ISP Management",
    copy: "Subscriber, billing, support, and payment flows for internet service providers.",
    cta: "#consult",
  },
  {
    id: "payments",
    icon: "fas fa-credit-card",
    title: "Payment Gateway & Integration",
    copy: "Collections, disbursements, sandboxes, callbacks, and reconciliation-aware APIs.",
    cta: "#consult",
  },
  {
    id: "sms",
    icon: "fas fa-sms",
    title: "Enterprise SMS Platforms",
    copy: "Admin consoles, reseller portals, bulk messaging, and API layers.",
    cta: "#consult",
  },
  {
    id: "observability",
    icon: "fas fa-chart-line",
    title: "Monitoring, Profiling & Observability",
    copy: "Application monitoring, browser observability, analytics, alerts, and profiling across development, staging, and production.",
    cta: "#consult",
  },
  {
    id: "sandbox",
    icon: "fas fa-flask",
    title: "Testing, Sandbox & Release Engineering",
    copy: "Sandbox environments, performance testing, build scenarios, custom assertions, and release-readiness support.",
    cta: "#consult",
  },
];

export const approachSteps = [
  { title: "Discover & align", copy: "Workshops to map workflows, compliance, and success metrics before build starts." },
  { title: "Design the experience", copy: "Wireframes, UI systems, and branded assets as the single source of truth." },
  { title: "Build & integrate", copy: "Laravel, React, REST APIs, SMS/WhatsApp/payment hooks tested on real workflows." },
  { title: "Test, sandbox & validate", copy: "Staging, sandbox environments, performance scenarios, assertions, and release checks before launch." },
  { title: "Launch & support", copy: "VPS or shared hosting, monitoring, alerts, training, runbooks, and production iteration." },
];

export const blogStats = [
  { value: "4+", label: "Years leadership" },
  { value: "10+", label: "Relationships" },
  { value: "25+", label: "Platforms" },
  { value: "15", label: "Featured builds" },
];

export const blogTags = [
  "WebDev",
  "SystemDesign",
  "UIUX",
  "ITSupport",
  "Accounting",
  "Automation",
  "WhatsApp",
  "CloudOps",
  "AIIntegration",
];

export const serviceSpotlights = [
  {
    title: "Web & System Design",
    description: "Custom CRMs, portals, and bilingual UX journeys engineered with Laravel, React, and secure APIs.",
    link: "services.html",
    label: "See how we ship →",
  },
  {
    title: "Graphic & UI/UX Design",
    description: "Brand systems, dashboards, and design systems crafted for smooth handoff to engineering.",
    link: "services.html#uiux",
    label: "Explore design ops →",
  },
  {
    title: "IT Support & Accounting",
    description: "Always-on support paired with computerized accounting automations tuned for African finance teams.",
    link: "contact.html",
    label: "Schedule a consult →",
  },
  {
    title: "AI Integration & Automation",
    description: "Embed OpenAI copilots, WhatsApp bots, and voice agents into your workflow without breaking existing systems.",
    link: "services.html#ai",
    label: "Plan an AI rollout →",
  },
];

export const solutionStories = [
  {
    client: "Active Targets — e-commerce",
    industry: "Live · E-commerce",
    image: "img/case-studies/active-targets.jpg",
    featured: true,
    challenge: "Needed a production storefront and admin for Tanzania-made AR500 targets — catalog, cart, coupons, CMS, and orders.",
    solution: "Shipped Laravel + Filament e-commerce: shop, checkout, admin CMS, and hardened Namecheap production deploy with performance and security hardening.",
    outcome: "Live commerce channel at activetargets.org with admin ops ready for daily sales.",
    services: ["Laravel", "Filament", "E-commerce", "Checkout"],
    cta_url: "services.html#ecommerce",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://activetargets.org/",
  },
  {
    client: "imartListener — Android desk app",
    industry: "Live · Flutter / SMS desk",
    image: "img/case-studies/imart-listener-login.jpg",
    featured: true,
    challenge: "iMart Group needed an on-device desk to capture customer SMS and WhatsApp, then sync conversations for agent replies.",
    solution: "Launched Flutter Android Listener with inbox sync to API, reply templates/bulk, and social phone lookup — paired with imartPortal + Laravel listenerBackend.",
    outcome: "Production business desk app feeding the live portal workflow (same account as the web desk).",
    services: ["Flutter", "SMS/WhatsApp", "Laravel API"],
    cta_url: "services.html#sms",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://imartlistener.lipapay.co.tz/",
  },
  {
    client: "imartPortal — business message desk",
    industry: "Live · Portal (logged in)",
    image: "img/case-studies/imart-listener-portal.jpg",
    featured: true,
    challenge: "Agents needed a secure web desk for conversations, outgoing messages, templates, sender IDs, and SMS settings alongside the Listener phone app.",
    solution: "Delivered imartPortal — Dashboard, Conversations, Outgoing, Templates, Social lookups, Incoming log, Sender ID, and SMS settings for the client workspace.",
    outcome: "Logged-in business message desk live at imartlistener.lipapay.co.tz, paired with the Android Listener app.",
    services: ["PHP", "MySQL", "SMS ops", "Portal"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://imartlistener.lipapay.co.tz/",
  },
  {
    client: "iMart SMS Portal",
    industry: "Live · Enterprise SMS",
    image: "img/case-studies/imart-listener-app-landing.jpg",
    featured: true,
    challenge: "Operations needed a clear entry point to sign in to the portal and download the Android Listener for the phone that receives customer messages.",
    solution: "Shipped the imartPortal landing experience — Sign in, Open portal, and Download Android app — with shared portal credentials for web and mobile.",
    outcome: "Unified onboarding path for desk agents: web portal + Listener app from one branded flow.",
    services: ["Portal UX", "Android handoff", "SMS ops"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://imartlistener.lipapay.co.tz/",
  },
  {
    client: "LipaPay Portal — collections",
    industry: "Live · Payments",
    image: "img/case-studies/lipapay-portal.jpg",
    featured: true,
    challenge: "Merchants needed a collections portal covering MNO, USSD, and card flows with secure checkout.",
    solution: "Built LipaPay Ver2 portal with API integration, secure checkout, and production support for iMartGroup payment operations.",
    outcome: "Live collections portal at portal.lipapay.co.tz.",
    services: ["Laravel", "Payment gateway", "MNO"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://portal.lipapay.co.tz/",
  },
  {
    client: "Lipa Wakala — agent back office",
    industry: "Live · Payments / agents",
    image: "img/case-studies/lipa-wakala-dashboard.jpg",
    featured: true,
    challenge: "Agents and admins needed a logged-in back office for POS status, users, inventory, complaints, activity logs, and API management.",
    solution: "Delivered the Lipa Wakala dashboard — organisation setup, inventory, support, system logs, and API management in one agent operations desk.",
    outcome: "Logged-in agent back office with live POS and activity visibility for payment operations.",
    services: ["Laravel", "Agent ops", "Payment gateway"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "Lipa Airtime",
    industry: "Live · FinTech / airtime",
    image: "img/case-studies/lipa-airtime.jpg",
    challenge: "Needed wallet purchase, bulk Excel top-ups, and role-based dashboards for merchants and finance.",
    solution: "Launched Laravel airtime platform with recharge callbacks and merchant/finance dashboards.",
    outcome: "Live airtime operations at airtime.lipapay.co.tz.",
    services: ["Laravel", "Airtime API", "Callbacks"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://airtime.lipapay.co.tz/",
  },
  {
    client: "Lipa Disbursement",
    industry: "Live · FinTech / payouts",
    image: "img/case-studies/lipa-disbursement.jpg",
    challenge: "Required outbound mobile-wallet payouts with status polling and merchant reconciliation.",
    solution: "Delivered Laravel disbursement engine with callbacks, polling, and reconciliation-aware payout flows.",
    outcome: "Live payout operations at disbursement.lipapay.co.tz.",
    services: ["Laravel", "Disbursement", "APIs"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://disbursement.lipapay.co.tz/",
  },
  {
    client: "LipaPay sandbox — iMartGroup",
    industry: "Hosted sandbox · Logged-in workspace",
    image: "img/case-studies/lipapay-sandbox.jpg",
    challenge: "Developers needed a staging hub and authenticated merchant workspace before mobile-money flows went to production.",
    solution: "Built Sandbox_LipaPay in iMartGroup Projects — developer docs hub plus logged-in merchant workspace (Testing Lab, Live APIs, Keys, Environments, Webhooks).",
    outcome: "Teams browse sandbox docs and sign in to the merchant workspace at sandbox.lipapay.co.tz before go-live.",
    services: ["Laravel", "REST APIs", "Shared hosting", "Sandbox"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://sandbox.lipapay.co.tz/",
  },
  {
    client: "VLL Admin — Victoria Lush",
    industry: "Live · Enterprise SMS",
    image: "img/case-studies/vll-admin.jpg",
    featured: true,
    challenge: "Needed central admin for users, SMS operations, and platform configuration on a reliable production host.",
    solution: "Built VLL Admin (Laravel) as part of the Victoria Lush stack deployed on Linux VPS with SSL and handover runbooks.",
    outcome: "Production admin used for daily SMS platform configuration and operations.",
    services: ["Laravel", "MySQL", "Blade", "Linux VPS"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "VLL SMS — company portal",
    industry: "Live · Company portal",
    image: "img/case-studies/vll-sms.jpg",
    featured: true,
    challenge: "Customers and operators needed a portal for SMS campaigns, contacts, templates, and delivery history.",
    solution: "Delivered the Victoria Lush company portal (VLL SMS) on production Linux VPS with documented environment config.",
    outcome: "Live customer-facing SMS portal supporting campaigns and delivery tracking.",
    services: ["Laravel", "Company portal", "Linux VPS"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "SMS Ver 1 — administrator",
    industry: "Live · SMS ecosystem",
    image: "img/case-studies/smsver1-admin.jpg",
    challenge: "Legacy SMS operations needed agent, reseller, pricing, and credit allocation controls.",
    solution: "Maintained and operated the SmSver1 administrator console (PHP/MySQL/SMPP) within the Victoria Lush SMS ecosystem.",
    outcome: "Reseller and credit workflows continue to run for production SMS operations.",
    services: ["PHP", "MySQL", "SMPP"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "Savanna Fibre — ISP digital",
    industry: "Live · ISP management",
    image: "img/case-studies/savanna-fibre.jpg",
    featured: true,
    challenge: "Fibre customers needed clear packages, coverage enquiry, shops, lead capture, and support journeys.",
    solution: "Built the ISP acquisition and ops-facing digital experience with residential/business packages, coverage, and lead forms — extended by the SavannaFibreDigital Laravel stack.",
    outcome: "Live ISP front door at savannafibre.co.tz with local Laravel management stack under development.",
    services: ["ISP management", "Laravel", "Lead forms"],
    cta_url: "services.html#isp",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://www.savannafibre.co.tz/",
  },
  {
    client: "iMartGroup Leave System (ELMS)",
    industry: "Live · HR / operations",
    image: "img/case-studies/elsm-live.jpg",
    challenge: "Employees and admins needed leave applications, balances, approvals, and reporting in one secure system.",
    solution: "Delivered Laravel ELMS with employee and administrator portals, approvals, and reporting.",
    outcome: "Production leave workflow at leave.imartgroup.co.tz.",
    services: ["Laravel", "Blade", "HR workflow"],
    cta_url: "services.html#systems",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://leave.imartgroup.co.tz/",
  },
  {
    client: "Fee Tracking & Reminder (FTRS)",
    industry: "Delivered · Education / accounting ops",
    image: "img/case-studies/fee-tracking.jpg",
    challenge: "Mbonea Secondary School staff needed fee records, receipts, and parent reminders without spreadsheet chaos.",
    solution: "Built a Laravel staff portal to track fees, record payments, issue receipts, and send parent reminders.",
    outcome: "Clearer fee visibility and parent communication from one secure system.",
    services: ["Laravel", "Accounting ops", "Reminders"],
    cta_url: "services.html#accounting",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "CakeZone — bakery admin",
    industry: "Demo · Operations software",
    image: "img/case-studies/cakezone.jpg",
    challenge: "Needed shop management for cakes and orders — catalog, customers, and an admin panel.",
    solution: "Built Laravel + Filament bakery admin for catalog, customers, and order workflows.",
    outcome: "Demonstrates Filament admin patterns reusable for retail and SMB operations systems.",
    services: ["Laravel", "Filament", "MySQL"],
    cta_url: "services.html#systems",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
];
