/** Data mirrored from PageController + fintech service catalogue */
export const serviceStats = [
  { value: "4+", label: "Years leadership" },
  { value: "10+", label: "Relationships" },
  { value: "25+", label: "Platforms" },
  { value: "10", label: "Service lines" },
];

export const services = [
  {
    id: "core-banking",
    icon: "fas fa-university",
    title: "Microfinance & Core Banking",
    copy: "Module configuration, loan/savings workflows, GL mapping review, and EOD batch troubleshooting within authorised platform scope.",
    cta: "#consult",
  },
  {
    id: "channels",
    icon: "fas fa-mobile-alt",
    title: "Digital Banking Channels",
    copy: "Internet Banking, Flutter mobile, agency POS, USSD, and merchant journeys with OTP and REST/Swagger integration.",
    cta: "#consult",
  },
  {
    id: "payments",
    icon: "fas fa-credit-card",
    title: "Integrations & Payments",
    copy: "Mobile money gateways, developer sandboxes, callbacks, and reconciliation-aware collection/disbursement flows.",
    cta: "#consult",
  },
  {
    id: "ecommerce",
    icon: "fas fa-shopping-cart",
    title: "E-Commerce Solutions",
    copy: "Storefronts, inventory, cart, checkout, and payment gateways for direct digital sales channels.",
    cta: "#consult",
  },
  {
    id: "enterprise",
    icon: "fas fa-laptop-code",
    title: "Custom Enterprise Software",
    copy: "Tailored web/mobile workflows, approval chains, HR platforms, and business portals on Laravel + React.",
    cta: "#consult",
  },
  {
    id: "web",
    icon: "fas fa-globe",
    title: "Web & Portal Design",
    copy: "Corporate web applications, customer portals, administrative dashboards, and intranets.",
    cta: "#consult",
  },
  {
    id: "ai",
    icon: "fas fa-robot",
    title: "AI Integration & Automation",
    copy: "Enterprise knowledge assistants, document classification, and support routing workflows.",
    cta: "#consult",
  },
  {
    id: "support",
    icon: "fas fa-headset",
    title: "IT Support & NOC",
    copy: "Monitoring, database performance tuning, remote support, and incident management for high availability.",
    cta: "#consult",
  },
  {
    id: "uiux",
    icon: "fas fa-palette",
    title: "Graphic Design & UI/UX",
    copy: "Wireframing, prototypes, design systems, visual branding, and accessible digital assets.",
    cta: "about.html",
  },
  {
    id: "hosting",
    icon: "fas fa-server",
    title: "Hosting & Infrastructure",
    copy: "Linux VPS, IIS, SSL, DNS, and backup routines — proven on Victoria Lush and iMartGroup LipaPay deployments.",
    cta: "#consult",
  },
];

export const approachSteps = [
  { title: "Discover & align", copy: "Workshops to map workflows, compliance, and success metrics before build starts." },
  { title: "Design the experience", copy: "Wireframes, UI systems, and branded assets as the single source of truth." },
  { title: "Build & integrate", copy: "Laravel, React, REST APIs, SMS/WhatsApp/payment hooks tested on real workflows." },
  { title: "Launch & support", copy: "VPS or shared hosting, training, runbooks, and production iteration." },
];

export const blogStats = [
  { value: "4+", label: "Years leadership" },
  { value: "10+", label: "Relationships" },
  { value: "25+", label: "Platforms" },
  { value: "14", label: "Featured builds" },
];

export const blogTags = [
  "WebDev",
  "SystemDesign",
  "UIUX",
  "ITSupport",
  "Accounting",
  "Automation",
  "WhatsApp",
  "CloudOps",
  "AIIntegration",
];

export const serviceSpotlights = [
  {
    title: "Web & System Design",
    description: "Custom CRMs, portals, and bilingual UX journeys engineered with Laravel, React, and secure APIs.",
    link: "services.html",
    label: "See how we ship →",
  },
  {
    title: "Graphic & UI/UX Design",
    description: "Brand systems, dashboards, and design systems crafted for smooth handoff to engineering.",
    link: "services.html#uiux",
    label: "Explore design ops →",
  },
  {
    title: "IT Support & Accounting",
    description: "Always-on support paired with computerized accounting automations tuned for African finance teams.",
    link: "contact.html",
    label: "Schedule a consult →",
  },
  {
    title: "AI Integration & Automation",
    description: "Embed OpenAI copilots, WhatsApp bots, and voice agents into your workflow without breaking existing systems.",
    link: "services.html#ai",
    label: "Plan an AI rollout →",
  },
];

export const solutionStories = [
  {
    client: "Active Targets — e-commerce",
    industry: "Live · E-commerce",
    image: "img/case-studies/active-targets.jpg",
    featured: true,
    challenge: "Needed a production storefront and admin for Tanzania-made AR500 targets — catalog, cart, coupons, CMS, and orders.",
    solution: "Shipped Laravel + Filament e-commerce: shop, checkout, admin CMS, and hardened Namecheap production deploy with performance and security hardening.",
    outcome: "Live commerce channel at activetargets.org with admin ops ready for daily sales.",
    services: ["Laravel", "Filament", "E-commerce", "Checkout"],
    cta_url: "services.html#ecommerce",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://activetargets.org/",
  },
  {
    client: "imartListener — Android desk app",
    industry: "Live · Flutter / SMS desk",
    image: "img/case-studies/imart-listener-login.jpg",
    featured: true,
    challenge: "iMart Group needed an on-device desk to capture customer SMS and WhatsApp, then sync conversations for agent replies.",
    solution: "Launched Flutter Android Listener with inbox sync to API, reply templates/bulk, and social phone lookup — paired with imartPortal + Laravel listenerBackend.",
    outcome: "Production business desk app feeding the live portal workflow (same account as the web desk).",
    services: ["Flutter", "SMS/WhatsApp", "Laravel API"],
    cta_url: "services.html#channels",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://imartlistener.lipapay.co.tz/",
  },
  {
    client: "imartPortal — business message desk",
    industry: "Live · Portal (logged in)",
    image: "img/case-studies/imart-listener-portal.jpg",
    featured: true,
    challenge: "Agents needed a secure web desk for conversations, outgoing messages, templates, sender IDs, and SMS settings alongside the Listener phone app.",
    solution: "Delivered imartPortal — Dashboard, Conversations, Outgoing, Templates, Social lookups, Incoming log, Sender ID, and SMS settings for the client workspace.",
    outcome: "Logged-in business message desk live at imartlistener.lipapay.co.tz, paired with the Android Listener app.",
    services: ["PHP", "MySQL", "SMS ops", "Portal"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://imartlistener.lipapay.co.tz/",
  },
  {
    client: "iMart SMS Portal",
    industry: "Live · Enterprise SMS",
    image: "img/case-studies/imart-listener-app-landing.jpg",
    featured: true,
    challenge: "Operations needed a clear entry point to sign in to the portal and download the Android Listener for the phone that receives customer messages.",
    solution: "Shipped the imartPortal landing experience — Sign in, Open portal, and Download Android app — with shared portal credentials for web and mobile.",
    outcome: "Unified onboarding path for desk agents: web portal + Listener app from one branded flow.",
    services: ["Portal UX", "Android handoff", "SMS ops"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://imartlistener.lipapay.co.tz/",
  },
  {
    client: "LipaPay Portal — collections",
    industry: "Live · FinTech / payments",
    image: "img/case-studies/lipapay-portal.jpg",
    featured: true,
    challenge: "Merchants needed a collections portal covering MNO, bank, USSD, and card flows with secure checkout.",
    solution: "Built LipaPay Ver2 portal with API integration, secure checkout, and production support for iMartGroup payment operations.",
    outcome: "Live collections channel at portal.lipapay.co.tz.",
    services: ["Laravel", "Payments API", "MNO/Bank"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://portal.lipapay.co.tz/",
  },
  {
    client: "Lipa Airtime",
    industry: "Live · FinTech / airtime",
    image: "img/case-studies/lipa-airtime.jpg",
    challenge: "Needed wallet purchase, bulk Excel top-ups, and role-based dashboards for merchants and finance.",
    solution: "Launched Laravel airtime platform with recharge callbacks and merchant/finance dashboards.",
    outcome: "Live airtime operations at airtime.lipapay.co.tz.",
    services: ["Laravel", "Airtime API", "Callbacks"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://airtime.lipapay.co.tz/",
  },
  {
    client: "Lipa Disbursement",
    industry: "Live · FinTech / payouts",
    image: "img/case-studies/lipa-disbursement.jpg",
    challenge: "Required outbound mobile-wallet and bank payouts with status polling and merchant reconciliation.",
    solution: "Delivered Laravel disbursement engine with callbacks, polling, and reconciliation-aware payout flows.",
    outcome: "Live payout operations at disbursement.lipapay.co.tz.",
    services: ["Laravel", "Disbursement", "APIs"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://disbursement.lipapay.co.tz/",
  },
  {
    client: "LipaPay sandbox — iMartGroup",
    industry: "Hosted sandbox · Logged-in workspace",
    image: "img/case-studies/lipapay-sandbox.jpg",
    challenge: "Developers needed a staging hub and authenticated merchant workspace before mobile-money flows went to production.",
    solution: "Built Sandbox_LipaPay in iMartGroup Projects — developer docs hub plus logged-in merchant workspace (Testing Lab, Live APIs, Keys, Environments, Webhooks).",
    outcome: "Teams browse sandbox docs and sign in to the merchant workspace at sandbox.lipapay.co.tz before go-live.",
    services: ["Laravel", "REST APIs", "Shared hosting", "Sandbox"],
    cta_url: "services.html#payments",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://sandbox.lipapay.co.tz/",
  },
  {
    client: "VLL Admin — Victoria Lush",
    industry: "Live · Enterprise SMS",
    image: "img/case-studies/vll-admin.jpg",
    featured: true,
    challenge: "Needed central admin for users, SMS operations, and platform configuration on a reliable production host.",
    solution: "Built VLL Admin (Laravel) as part of the Victoria Lush stack deployed on Linux VPS with SSL and handover runbooks.",
    outcome: "Production admin used for daily SMS platform configuration and operations.",
    services: ["Laravel", "MySQL", "Blade", "Linux VPS"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "VLL SMS — company portal",
    industry: "Live · Company portal",
    image: "img/case-studies/vll-sms.jpg",
    featured: true,
    challenge: "Customers and operators needed a portal for SMS campaigns, contacts, templates, and delivery history.",
    solution: "Delivered the Victoria Lush company portal (VLL SMS) on production Linux VPS with documented environment config.",
    outcome: "Live customer-facing SMS portal supporting campaigns and delivery tracking.",
    services: ["Laravel", "Company portal", "Linux VPS"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "SMS Ver 1 — administrator",
    industry: "Live · SMS ecosystem",
    image: "img/case-studies/smsver1-admin.jpg",
    challenge: "Legacy SMS operations needed agent, reseller, pricing, and credit allocation controls.",
    solution: "Maintained and operated the SmSver1 administrator console (PHP/MySQL/SMPP) within the Victoria Lush SMS ecosystem.",
    outcome: "Reseller and credit workflows continue to run for production SMS operations.",
    services: ["PHP", "MySQL", "SMPP"],
    cta_url: "contact.html",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "Savanna Fibre — ISP digital",
    industry: "Live · ISP / web",
    image: "img/case-studies/savanna-fibre.jpg",
    challenge: "Fibre customers needed clear packages, coverage enquiry, shops, lead capture, and support journeys.",
    solution: "Built the marketing and conversion site with residential/business packages, coverage, and lead forms.",
    outcome: "Live acquisition front door at savannafibre.co.tz.",
    services: ["HTML/CSS/JS", "ISP UX", "Lead forms"],
    cta_url: "services.html#web",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://www.savannafibre.co.tz/",
  },
  {
    client: "iMartGroup Leave System (ELMS)",
    industry: "Live · HR / operations",
    image: "img/case-studies/elsm-live.jpg",
    challenge: "Employees and admins needed leave applications, balances, approvals, and reporting in one secure system.",
    solution: "Delivered Laravel ELMS with employee and administrator portals, approvals, and reporting.",
    outcome: "Production leave workflow at leave.imartgroup.co.tz.",
    services: ["Laravel", "Blade", "HR workflow"],
    cta_url: "services.html#enterprise",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
    live_url: "https://leave.imartgroup.co.tz/",
  },
  {
    client: "Fee Tracking & Reminder (FTRS)",
    industry: "Delivered · Education",
    image: "img/case-studies/fee-tracking.jpg",
    challenge: "Mbonea Secondary School staff needed fee records, receipts, and parent reminders without spreadsheet chaos.",
    solution: "Built a Laravel staff portal to track fees, record payments, issue receipts, and send parent reminders.",
    outcome: "Clearer fee visibility and parent communication from one secure system.",
    services: ["Laravel", "Receipts", "Reminders"],
    cta_url: "services.html#enterprise",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
  {
    client: "CakeZone — bakery admin",
    industry: "Demo · Operations software",
    image: "img/case-studies/cakezone.jpg",
    challenge: "Needed shop management for cakes and orders — catalog, customers, and an admin panel.",
    solution: "Built Laravel + Filament bakery admin for catalog, customers, and order workflows.",
    outcome: "Demonstrates Filament admin patterns reusable for retail and SMB operations systems.",
    services: ["Laravel", "Filament", "MySQL"],
    cta_url: "services.html#enterprise",
    portfolio_url: "https://sarahgordon895.github.io/sarahgordon.github.io/",
  },
];
